config/routes.rb
SimuladorPreco::Application.routes.draw do
  resources :vpsa_produtos

  get "tutorial/index"

  get "home/index"

  get "oauth/authorization"
  get "oauth/callback"
  get "simulacao_produtos/proxima_pagina"
  get "simulacao_produtos/pagina_anterior"
  get "simulacao_produtos/index"
  delete "oauth/logout"

  resources :simulacao_produtos
  resources :simulacaos

     match 'tutorial' => 'tutorial#index'
     match 'tutorial' => 'tutorial#index'
     

   root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if usuario_logado
  		redirect_to :controller=>'simulacao_produtos', :action => 'index'
  	else
  		redirect_to :controller=>'oauth', :action => 'authorization'
  	end
  end

  def usuario
    session[:usuario]
  end
  
  def usuario_logado
    !usuario.nil?
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

  </head>
  <body>
    <% if usuario_logado? %>

      <h3>Usuario:  <%= usuario[:nome_terceiro] %></h3>
      <%= button_to "Sair", oauth_logout_path, :class => 'btn',:method => :delete %>
      <div align='center'>

    <% else %>

      <h1>O usuário ainda não autorizou seu aplicativo</h1>
      <%= link_to oauth_authorization_path %>

    <% end %>
  		
      
  
  <section>
  
    <p align ='center'>

     
      <%= link_to "Como Calcular?", "/tutorial", :class =>'botao_home', :style=>'color:#FFFFFF; top:180px'  %>
       <%= link_to "Simular", "/simulacao_produtos", :class =>'botao_home', :style=>'color:#FFFFFF; top:180px '  %>
      <p/>

    	</div>
    </section>

  </body>
  </html>